const nodemailer = require('nodemailer');
const { getDb } = require('../db/database');

function getConfig() {
  const db = getDb();
  const get = (key) => db.prepare("SELECT value FROM app_config WHERE key = ?").get(key)?.value || process.env[key];
  return {
    host: get('SMTP_HOST') || 'smtp.gmail.com',
    port: parseInt(get('SMTP_PORT') || '587', 10),
    user: get('SMTP_USER'),
    pass: (get('SMTP_PASS') || '').replace(/\s/g, ''), // strip spaces from Google App Passwords
    from: get('SMTP_FROM'),
  };
}

function buildHtmlEmail(analysis, diff, scheduleLabel) {
  const data = typeof analysis.result_json === 'string' ? JSON.parse(analysis.result_json) : analysis.result_json;
  const columns = data.columns || [];
  const rows = data.rows || [];
  const date = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });

  let changedCount = 0, newCount = 0, removedCount = 0;
  if (diff) {
    for (const field of Object.values(diff)) {
      for (const cell of Object.values(field)) {
        if (cell.status === 'changed') changedCount++;
        else if (cell.status === 'new') newCount++;
        else if (cell.status === 'removed') removedCount++;
      }
    }
  }

  const headerCells = columns.map(col => `<th style="padding:8px 12px;background:#1e293b;color:#fff;text-align:left;white-space:nowrap;">${col}</th>`).join('');

  const bodyRows = rows.map(row => {
    const cells = columns.map(col => {
      if (col === 'Field') return `<td style="padding:8px 12px;font-weight:600;background:#f8fafc;white-space:nowrap;">${row[col] || ''}</td>`;
      const cellDiff = diff?.[row.Field]?.[col];
      let bg = '#fff';
      let content = row[col] || '';
      if (cellDiff?.status === 'changed') {
        bg = '#fef3c7';
        content = `<s style="color:#9ca3af;font-size:11px;">${cellDiff.old}</s><br>${cellDiff.new}`;
      } else if (cellDiff?.status === 'new') {
        bg = '#d1fae5';
      } else if (cellDiff?.status === 'removed') {
        bg = '#fee2e2';
      }
      return `<td style="padding:8px 12px;background:${bg};vertical-align:top;">${content}</td>`;
    }).join('');
    return `<tr>${cells}</tr>`;
  }).join('');

  return `<!DOCTYPE html><html><body style="font-family:system-ui,sans-serif;max-width:1200px;margin:0 auto;padding:20px;">
<div style="background:#1e293b;color:#fff;padding:20px 24px;border-radius:8px 8px 0 0;">
  <h1 style="margin:0;font-size:22px;">RivalScope</h1>
  <p style="margin:4px 0 0;color:#94a3b8;">${scheduleLabel} — ${date}</p>
</div>
<div style="background:#f0f9ff;padding:16px 24px;border-left:4px solid #0ea5e9;">
  <p style="margin:0;color:#0c4a6e;">${data.summary || ''}</p>
</div>
${diff ? `<div style="padding:16px 24px;background:#fff;border-bottom:1px solid #e2e8f0;">
  <strong>Changes:</strong>
  <span style="background:#fef3c7;padding:2px 8px;border-radius:12px;margin:0 4px;">${changedCount} changed</span>
  <span style="background:#d1fae5;padding:2px 8px;border-radius:12px;margin:0 4px;">${newCount} new</span>
  <span style="background:#fee2e2;padding:2px 8px;border-radius:12px;margin:0 4px;">${removedCount} removed</span>
</div>` : ''}
<div style="overflow-x:auto;">
  <table style="width:100%;border-collapse:collapse;font-size:13px;">
    <thead><tr>${headerCells}</tr></thead>
    <tbody>${bodyRows}</tbody>
  </table>
</div>
<div style="padding:16px 24px;background:#f8fafc;color:#64748b;font-size:12px;border-radius:0 0 8px 8px;">
  This analysis was auto-generated by RivalScope. To modify this schedule, visit your RivalScope dashboard.
</div>
</body></html>`;
}

async function send(emailTo, analysis, diff, scheduleLabel) {
  const { host, port, user, pass, from } = getConfig();
  if (!user || !pass || !from) {
    console.error('SMTP not configured — set SMTP_USER, SMTP_PASS, SMTP_FROM');
    return;
  }

  const transporter = nodemailer.createTransport({
    host,
    port,
    secure: port === 465,
    auth: { user, pass },
  });

  const date = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const subject = `RivalScope: ${scheduleLabel} — Update ${date}`;
  const html = buildHtmlEmail(analysis, diff, scheduleLabel);

  const attachments = [];
  if (analysis.result_csv) {
    attachments.push({
      content: analysis.result_csv,
      filename: `rivalscope-${date.replace(/ /g, '-')}.csv`,
      contentType: 'text/csv',
    });
  }

  await transporter.sendMail({ from, to: emailTo, subject, html, attachments });
}

module.exports = { send };
