const FIELD_TEMPLATES = {
  DSP: [
    "Inventory Types (Display/Video/CTV/Audio/DOOH/Native)",
    "Minimum Managed Spend / Self-serve Availability",
    "Bidding Algorithm (Rules-based / ML / Custom Scripts)",
    "Deal Types Supported (PG / PMP / Open Auction / Preferred)",
    "Audience Targeting (1P/2P/3P, Contextual, Behavioral, Geo, Device)",
    "Identity Solutions (UID2 / ID5 / RampID / LiveRamp / Cookieless)",
    "Cross-device Graph (Deterministic / Probabilistic)",
    "Creative Formats & DCO Support",
    "Custom Audience Upload & Lookalike Modeling",
    "Brand Safety & Viewability Partners (IAS / DV / MOAT)",
    "Frequency Capping (Session / Daily / Cross-device)",
    "Attribution Models (Last touch / Multi-touch / View-through)",
    "Reporting Granularity & Real-time Dashboard",
    "Key Integrations & Data Partners",
    "Pricing / Tech Fee Model",
    "Self-serve vs Managed",
    "Geographic Coverage",
    "Company Stage / Key Customers",
  ],
  SSP: [
    "Inventory Types Monetized",
    "Publisher Revenue Share / Take Rate",
    "Demand Partner Count (DSP integrations)",
    "Deal Types (PMP / PG / Open Auction)",
    "Floor Price Management (Dynamic floors / Unified auction)",
    "Header Bidding Support (Prebid.js / Prebid Server)",
    "Auction Type (First-price / Second-price)",
    "Traffic Quality & IVT Filtering",
    "Ads.txt / Sellers.json Compliance",
    "Publisher Self-serve Control Panel",
    "Supply Path Optimization (SPO) Features",
    "OpenRTB Version Support",
    "Identity / Cookieless Readiness",
    "CTV / Video / Mobile Coverage",
    "Reporting & Analytics",
    "White-label / Reseller Option",
    "Pricing Model",
    "Key Publisher Customers",
  ],
  AD_SERVER: [
    "Ad Server Type (First-party / Third-party / Hybrid)",
    "Decisioning Engine (Rule-based / Yield-optimized / ML)",
    "VAST / VPAID / SIMID / VMAP Support",
    "Direct Deal & Guaranteed Delivery",
    "Programmatic Auction Integration",
    "SSAI / Ad Stitching Capability",
    "Creative Format Support",
    "Trafficking Workflow & Bulk Upload",
    "White-label / Multi-tenant / Reseller",
    "Self-serve Onboarding Time",
    "API Quality (REST / GraphQL / SDK)",
    "Cookieless & Privacy Readiness",
    "Reporting Granularity",
    "CDN Integrations (Akamai / CloudFront / Fastly)",
    "SLA / Uptime",
    "Deployment Model (Cloud / On-prem / Hybrid)",
    "Pricing Model",
    "Key Customers",
  ],
  SSAI_CTV: [
    "Insertion Type (CSAI / SSAI / Hybrid)",
    "VOD vs Live Stream Support",
    "Manifest Manipulation (HLS / DASH stitching)",
    "Ad Decision Latency (p50/p99)",
    "VAST / VPAID / SIMID Support",
    "Ad Pod & Break Management",
    "SCTE-35 Signal Handling (for live)",
    "Addressable TV / Linear Support",
    "Slate & Fallback Content",
    "Tracking & Quartile Beacons",
    "DRM Compatibility (Widevine / FairPlay / PlayReady)",
    "CDN & Origin Server Integrations",
    "CTV Device SDK Support (Roku / FireTV / AppleTV / SmartTV)",
    "Player Integrations (JWPlayer / Brightcove / VideoJS / Shaka)",
    "Streaming Protocols (HLS / DASH / Smooth)",
    "Interactive / Overlay Ad Support",
    "Companion Ads",
    "Cross-screen Measurement",
    "Scalability / QPS Capacity",
    "Deployment Model",
    "Pricing Model",
  ],
  DMP_IDENTITY: [
    "Identity Graph Type (Deterministic / Probabilistic / Hybrid)",
    "Cookieless Identity Solution (UID2 / ID5 / Cohort / FPD)",
    "Data Onboarding & CRM Match Rate",
    "Second-party Data Marketplace",
    "Clean Room Compatibility (AWS / InfoSum / Habu)",
    "Segment Taxonomy (Count & Depth)",
    "Real-time Segment Activation Latency",
    "Publisher vs Advertiser Primary Focus",
    "MMP Integrations (AppsFlyer / Adjust / Branch)",
    "Contextual Targeting Engine",
    "GDPR / CCPA / TCF 2.2 Compliance",
    "Data Retention Policies",
    "Pricing Model",
    "Key Customers",
  ],
  AD_QUALITY: [
    "IVT Detection (GIVT vs SIVT)",
    "MRC Accreditation Status",
    "Pre-bid vs Post-bid Protection",
    "Ad Malware / Malvertising Blocking",
    "Creative Quality Scanning",
    "Viewability Measurement Methodology",
    "Attention Metrics Support",
    "Brand Safety Categories (GARM aligned)",
    "Contextual Suitability Scoring",
    "Tag Monitoring & Piggybacking Detection",
    "Format Coverage (Display / Video / CTV / In-app)",
    "DSP / SSP Integrations",
    "Real-time vs Batch Reporting",
    "Better Ads Standards Compliance",
    "Pricing Model (CPM / % of spend / flat)",
    "Key Customers",
  ],
  CMP: [
    "IAB TCF Version (2.0 / 2.2 Certified)",
    "Google CMP Partner Program Certified",
    "Regulations Supported (GDPR / CCPA / CPRA / LGPD / PIPEDA)",
    "Auto Cookie Scanning & Discovery",
    "Banner Customization Depth",
    "A/B Testing for Consent UI",
    "Server-side Consent Signal Support",
    "Consent Mode v2 Integration",
    "DSR / DSAR Automation",
    "Geo-targeted Consent Rules",
    "CMP SDK (Web / Mobile / AMP)",
    "Audit Logging & Compliance Reporting",
    "Pricing Model (Free tier / Per domain / Enterprise)",
    "Key Differentiator",
  ],
  RETARGETING: [
    "Retargeting Window (Max lookback days)",
    "Environments (Web / App / CTV / DOOH)",
    "Performance Optimization Goals (CPC / CPA / ROAS / Installs)",
    "Product Catalog / Dynamic Feed Support",
    "Post-install Event Tracking",
    "MMP Integrations",
    "SKAdNetwork / iOS 14+ Support",
    "In-app Ad Format Support (Rewarded / Interstitial / Banner / Playable)",
    "Cross-device Retargeting",
    "Audience Suppression Lists",
    "Lookalike Modeling",
    "Pricing Model",
    "Minimum Spend",
    "Key Customers / Verticals",
  ],
  HEADER_BIDDING: [
    "Wrapper Type (Client-side / Server-side / Hybrid)",
    "Prebid.js Version Support & Custom Modules",
    "Prebid Server Support",
    "Number of Active Bidder Integrations",
    "Timeout Handling & Waterfall Fallback",
    "Price Granularity & Key-value Buckets",
    "Analytics Module",
    "A/B Testing (Floor prices / Config)",
    "Identity Module Support (UID2 / ID5)",
    "CTV / Video Prebid Support",
    "Open Source vs Proprietary",
    "Managed Service Option",
    "Pricing / Revenue Share",
  ],
  DOOH: [
    "Screen Network Size & Geography",
    "Venue Types (Transit / Retail / OOH / Billboards)",
    "Programmatic DSP Integrations",
    "Audience Measurement Methodology",
    "Creative Format Support (Static / Video / Dynamic)",
    "Dayparting & Context Targeting",
    "Real-time Bidding Support",
    "Minimum Spend",
    "Reporting & Attribution",
    "Pricing Model",
  ],
  AGENCY: [
    "Service Scope (Full-service / Specialized)",
    "Programmatic Capabilities",
    "CTV/Video Expertise",
    "Technology Stack / DSP Used",
    "Minimum Engagement Size",
    "Reporting & Transparency",
    "Pricing Model (% of spend / retainer / hybrid)",
    "Key Verticals Served",
    "Notable Clients",
    "Differentiator",
  ],
  CONTEXTUAL_ADVERTISING: [
    "Contextual Technology (NLP / CV / AI)",
    "Content Taxonomy Depth (IAB / custom / semantic)",
    "Video & CTV Content Understanding",
    "Real-time Signal Freshness",
    "Attention Metrics Integration",
    "Brand Safety & Competitor Detection",
    "Language & Multi-lingual Support",
    "DSP / Ad Server Integration Methods",
    "Cookieless & Privacy Readiness",
    "Keyword & Topic Exclusion Rules",
    "Pricing Model",
    "Key Customers / Verticals",
  ],
  CREATIVE_TECH: [
    "DCO Engine (Rule-based / ML / Multivariate)",
    "Ad Format Support (Display / Video / Native / Rich Media)",
    "Data Feed Integration (1P / product catalog / real-time pricing)",
    "Personalization Depth (geo / device / audience / weather / time)",
    "A/B Testing & Statistical Significance",
    "Studio / No-code Creation Tools",
    "HTML5 / Canvas / WebGL Support",
    "Creative QA & Preview Workflow",
    "Performance Insights (lift / CTR / conversion by variable)",
    "CTV / OTT Creative Delivery",
    "Compliance Scanning (malware / policy)",
    "Pricing Model",
  ],
  ATTRIBUTION_MEASUREMENT: [
    "Attribution Models (last-touch / MTA / algorithmic / time-decay)",
    "Touchpoint Coverage (online / offline / CRM / in-store)",
    "Incrementality Testing (holdout / geo-matched / matched market)",
    "MMM & Budget Optimization",
    "Cross-device User Journey Tracking",
    "Privacy-compliant Measurement (server-side / modeled conversions)",
    "MMP Integrations (AppsFlyer / Adjust / Branch / Kochava)",
    "Data Platform Integrations (GA4 / Mixpanel / Snowflake)",
    "Lookback Window Customization",
    "Reporting Latency (real-time / daily / weekly)",
    "Export & API Access",
    "Pricing Model",
  ],
  NATIVE_ADVERTISING: [
    "Inventory Types (in-feed / article recommendation / sponsored content)",
    "Supply Partner & Publisher Count",
    "Native Format Support (image+text / video / carousel / dynamic)",
    "Contextual Relevance Matching",
    "Viewability & Engagement Metrics",
    "Brand Safety & Publisher Controls",
    "Audience Targeting (demographic / interest / contextual / lookalike)",
    "Creative Upload & Bulk Trafficking",
    "Click & Engagement Tracking",
    "Pricing Model (CPM / CPC / CPA)",
    "Key Publisher Partners",
  ],
  BRAND_SAFETY: [
    "Detection Technology (keyword / ML NLP / computer vision)",
    "Category Taxonomy (GARM-aligned / custom depth)",
    "Sensitivity Level Customization",
    "Pre-bid vs Post-bid Coverage",
    "News & Real-time Event Monitoring",
    "Competitor Detection & Blocking",
    "Format Coverage (Display / Video / Native / Audio / CTV / In-app)",
    "DSP & SSP Integrations",
    "Influencer & Social Vetting",
    "Remediation & Incident Reporting",
    "MRC Accreditation Status",
    "Pricing Model",
  ],
  PROGRAMMATIC_AUDIO: [
    "Audio Inventory Types (streaming / podcast / radio / smart speaker)",
    "Streaming Platform Integrations (Spotify / Apple Music / iHeart)",
    "Podcast Network Coverage",
    "Dynamic Ad Insertion Support",
    "Bidding & Deal Types (PMP / open auction / programmatic direct)",
    "Audience Targeting (behavioral / contextual / geo / device)",
    "Creative Format Requirements (15s / 30s / 60s / interactive)",
    "Attribution & Conversion Tracking",
    "Cross-channel Frequency Capping",
    "Measurement (completion rate / brand lift / engagement)",
    "Pricing Model & Minimum Spend",
  ],
  MOBILE_DSP: [
    "App Inventory Coverage & Categories",
    "Mobile Web Support (AMP / PWA)",
    "Mobile Bidding Algorithm",
    "MMP Integrations (AppsFlyer / Adjust / Branch / Singular)",
    "SKAdNetwork Version Support",
    "Device & OS Targeting (iOS / Android / version / make/model)",
    "Mobile Creative Formats (interstitial / rewarded / playable / native)",
    "App-to-app Retargeting",
    "Fraud Detection & IVT Filtering",
    "Install & In-app Event Attribution Latency",
    "Cross-device & CTV Extension",
    "Pricing Model (CPI / CPC / CPM / CPA)",
  ],
  PUBLISHER_MONETIZATION: [
    "Minimum Traffic Requirements",
    "Revenue Share / Take Rate",
    "Ad Unit Types (display / video / native / audio / outstream)",
    "Demand Access (DSP integrations / Google / Amazon / OpenX)",
    "Header Bidding Approach (managed / self-hosted / turnkey)",
    "Publisher Control Panel Features",
    "Cookieless & 1P Data Optimization",
    "Viewability & Brand Safety Reporting",
    "Direct Deal Facilitation",
    "Contextual Inventory Tagging",
    "Support Level (managed / self-serve / agency)",
    "Pricing Model",
  ],
  DATA_MARKETPLACE: [
    "Platform Type (clean room / open marketplace / hybrid)",
    "Data Source Coverage (2P / publisher / retail / telco)",
    "Identity Matching Technology (email / phone / UID2 / RampID / IP)",
    "Match Rate Benchmarks",
    "Use Cases (lookalike / attribution / audience segments / analytics)",
    "Clean Room Compatibility (AWS / InfoSum / Habu / Google Ads Data Hub)",
    "Onboarding Methods (file upload / API / pixel / CRM)",
    "Query & Activation Latency",
    "Destination Integrations (DSP / SSP / marketing cloud / analytics)",
    "Privacy & Compliance (GDPR / CCPA / data retention policies)",
    "Scale (max segment size / query complexity)",
    "Pricing Model",
  ],
  RETAIL_MEDIA: [
    "Retailer Partner Count & Shopper Data Scale",
    "Inventory Types (on-site search / product pages / email / offsite)",
    "Shopper Data Capabilities (purchase history / basket / loyalty tier)",
    "Audience Segments & Lookalike Modeling",
    "Attribution Model (click / view-through / in-store lift / sales lift)",
    "Self-serve Advertiser Tools",
    "Keyword & Search Targeting",
    "Creative Compliance Rules",
    "Competitive Separation Policies",
    "Performance Reporting (ROAS / conversion rate / impression share)",
    "Data Privacy & Brand Agreements",
    "Pricing Model (CPC / CPM / % commission)",
  ],
  INFLUENCER_CREATOR: [
    "Creator Network Size & Categories",
    "Creator Vetting (authenticity / engagement quality / brand safety)",
    "Campaign Management (briefing / approval / rights management)",
    "Audience Insights (demographics / interests / lookalike)",
    "Affiliate & Commerce Integration (links / codes / tracking)",
    "Performance Metrics (impressions / engagements / sentiment)",
    "Contract & Compliance (FTC disclosure / exclusivity / usage rights)",
    "Creator Payments (automated / escrow / commission split)",
    "Reporting & Attribution (promo code / UTM / pixel)",
    "Platform Coverage (Instagram / TikTok / YouTube / X / Twitch)",
    "Pricing Model",
  ],
  GENERAL: [
    "Product Category / Type",
    "Core Value Proposition",
    "Key Features",
    "Pricing Model",
    "Target Customer",
    "Integrations & Partnerships",
    "Compliance & Privacy",
    "Deployment Model",
    "Company Stage",
    "Key Differentiator",
  ],
};

const COMPANY_STRUCTURE_FIELDS = [
  "Company: Headcount",
  "Company: Founded",
  "Company: Total Funding Raised",
  "Company: Last Funding Round",
  "Company: HQ Location",
];

module.exports = { FIELD_TEMPLATES, COMPANY_STRUCTURE_FIELDS };
