[build]
builder = "NIXPACKS"

[setup]
installationCommand = "npm install && npm install --prefix frontend && npm install --prefix backend"

[phases.build]
dependsOn = ["setup"]
buildCommand = "npm run build"

[deploy]
startCommand = "node backend/index.js"
restartPolicyType = "ON_FAILURE"
