[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = ["nodejs"]
cmds = ["npm install && npm install --prefix frontend && npm install --prefix backend"]

[phases.build]
cmds = ["npm run build --prefix frontend"]

[deploy]
startCommand = "node backend/index.js"
